### ISSUE TITLE
Make error with OpenCV 2.4.9

### ISSUE THREAD

**Issue by rantonels** [kylemcdonald/FaceTracker#26] opened 2015-08-05 10:21 UTC
```
$ make -j8
g++ -MM -MT src/lib/Patch.o -MF src/lib/Patch.d -Wextra -Wall -pedantic-errors  -O3 -Wno-long-long  -I/usr/local/include -Iinclude/ src/lib/Patch.cc
g++ -MM -MT src/lib/FDet.o -MF src/lib/FDet.d -Wextra -Wall -pedantic-errors  -O3 -Wno-long-long  -I/usr/local/include -Iinclude/ src/lib/FDet.cc
g++ -MM -MT src/lib/PAW.o -MF src/lib/PAW.d -Wextra -Wall -pedantic-errors  -O3 -Wno-long-long  -I/usr/local/include -Iinclude/ src/lib/PAW.cc
g++ -MM -MT src/lib/Tracker.o -MF src/lib/Tracker.d -Wextra -Wall -pedantic-errors  -O3 -Wno-long-long  -I/usr/local/include -Iinclude/ src/lib/Tracker.cc
g++ -MM -MT src/exe/face_tracker.o -MF src/exe/face_tracker.d -Wextra -Wall -pedantic-errors  -O3 -Wno-long-long  -I/usr/local/include -Iinclude/ src/exe/face_tracker.cc
g++ -Wextra -Wall -pedantic-errors  -O3 -Wno-long-long  -c -o src/lib/FDet.o src/lib/FDet.cc -I/usr/local/include -Iinclude/
g++ -Wextra -Wall -pedantic-errors  -O3 -Wno-long-long  -c -o src/lib/Patch.o src/lib/Patch.cc -I/usr/local/include -Iinclude/
g++ -Wextra -Wall -pedantic-errors  -O3 -Wno-long-long  -c -o src/lib/PAW.o src/lib/PAW.cc -I/usr/local/include -Iinclude/
g++ -Wextra -Wall -pedantic-errors  -O3 -Wno-long-long  -c -o src/lib/Tracker.o src/lib/Tracker.cc -I/usr/local/include -Iinclude/
g++ -Wextra -Wall -pedantic-errors  -O3 -Wno-long-long  -c -o src/exe/face_tracker.o src/exe/face_tracker.cc -I/usr/local/include -Iinclude/
src/lib/PAW.cc: In member function ‘void FACETRACKER::PAW::Crop(cv::Mat&, cv::Mat&, cv::Mat&)’:
src/lib/PAW.cc:167:3: error: ‘remap’ is not a member of ‘cv’
   cv::remap(src,dst,_mapx,_mapy,CV_INTER_LINEAR); return;
   ^
src/lib/Tracker.cc: In member function ‘int FACETRACKER::Tracker::Track(cv::Mat, std::vector<int>&, int, int, double, double, bool)’:
src/lib/Tracker.cc:94:5: error: ‘cvtColor’ is not a member of ‘cv’
     cv::cvtColor(im,gray_,CV_BGR2GRAY);
     ^
src/lib/Tracker.cc: In member function ‘cv::Rect FACETRACKER::Tracker::ReDetect(cv::Mat&)’:
src/lib/Tracker.cc:141:3: error: ‘resize’ is not a member of ‘cv’
   cv::resize(im,small_,cv::Size(TSCALE*ww,TSCALE*hh),0,0,CV_INTER_LINEAR);
   ^
src/lib/Tracker.cc: In member function ‘cv::Rect FACETRACKER::Tracker::UpdateTemplate(cv::Mat&, cv::Mat&, bool)’:
src/lib/Tracker.cc:178:7: error: ‘resize’ is not a member of ‘cv’
       cv::resize(im,small_,cv::Size(TSCALE*ww,TSCALE*hh),0,0,CV_INTER_LINEAR);
       ^
Makefile:43: recipe for target 'src/lib/PAW.o' failed
make: *** [src/lib/PAW.o] Error 1
```

and it goes on like this. I have OpenCV 2.4.9 installed through the package manager.

**Comment by kylemcdonald** [comment] 2015-08-05 17:24
hi! thanks for issue report. which OS are you running -- is it ubuntu?

**Comment by rantonels** [comment] 2015-08-10 20:59
debian

**Comment by kylemcdonald** [comment] 2017-03-20 01:33
I think this was an issue of which OpenCV header was included. Closing as not able to reproduce / probably fixed.

**Closed by kylemcdonald** 2017-03-20 01:33 UTC
