### ISSUE TITLE
Running make on OSX gives error

### ISSUE THREAD

**Issue by azaman13** [kylemcdonald/FaceTracker#28] opened 2015-10-05 06:12 UTC
I installed open cv using brew. Then running make on FaceTracker  gives me these. Any idea please?

```
g++ -MM -MT src/lib/IO.o -MF src/lib/IO.d -Wextra -Wall -pedantic-errors -arch x86_64 -O3 -fopenmp  -I/usr/local/include -Isrc/lib src/lib/IO.cc
g++ -Wextra -Wall -pedantic-errors -arch x86_64 -O3 -fopenmp  -I/usr/local/include -Isrc/lib -c -o src/lib/IO.o src/lib/IO.cc 
In file included from src/lib/IO.cc:40:
In file included from src/lib/IO.h:42:
In file included from /usr/local/include/opencv2/opencv.hpp:56:
/usr/local/include/opencv2/ml/ml.hpp:674:9: error: anonymous types declared in an anonymous union are an extension [-Werror,-Wnested-anon-types]
        struct
        ^
/usr/local/include/opencv2/ml/ml.hpp:961:18: warning: 'CvForestTree::train' hides overloaded virtual functions [-Woverloaded-virtual]
    virtual bool train( CvDTreeTrainData* trainData, const CvMat* _subsample_idx, CvRTrees* forest );
                 ^
/usr/local/include/opencv2/ml/ml.hpp:867:18: note: hidden overloaded virtual function 'CvDTree::train' declared here: different number of parameters (2 vs 3)
    virtual bool train( CvMLData* trainData, CvDTreeParams params=CvDTreeParams() );
                 ^
/usr/local/include/opencv2/ml/ml.hpp:877:26: note: hidden overloaded virtual function 'CvDTree::train' declared here: different number of parameters (8 vs 3)
    CV_WRAP virtual bool train( const cv::Mat& trainData, int tflag,
                         ^
/usr/local/include/opencv2/ml/ml.hpp:1149:18: warning: 'CvBoostTree::train' hides overloaded virtual functions [-Woverloaded-virtual]
    virtual bool train( CvDTreeTrainData* trainData,
                 ^
/usr/local/include/opencv2/ml/ml.hpp:867:18: note: hidden overloaded virtual function 'CvDTree::train' declared here: different number of parameters (2 vs 3)
    virtual bool train( CvMLData* trainData, CvDTreeParams params=CvDTreeParams() );
                 ^
/usr/local/include/opencv2/ml/ml.hpp:877:26: note: hidden overloaded virtual function 'CvDTree::train' declared here: different number of parameters (8 vs 3)
    CV_WRAP virtual bool train( const cv::Mat& trainData, int tflag,
                         ^
2 warnings and 1 error generated.
make: *** [src/lib/IO.o] Error 1

```

**Comment by PatateCrue** [comment] 2016-05-30 19:17
Hello,

I have the same problem... Did you solved it?

Thanks

**Comment by GTorreil** [comment] 2016-11-02 09:17
Same problem .. Following that thread 👍

**Comment by kylemcdonald** [comment] 2017-03-20 01:32
Closing this as I can't reproduce.

**Closed by kylemcdonald** 2017-03-20 01:32 UTC
